### PR TITLE
#36 - curl publish, update meta file by tgz

### PR DESCRIPTION
**Pull request by genryxy**
Part of #36 
Implemented `CurlPublish`, updating meta file by uploaded tgz archive. 
Decreased test coverage values for jacoco (in next PR I'll add tests and increase the values).
Bumped dependency of testcontainers from `1.14.3` to `1.15.1` to fix ITs failings.

### CODE REVIEW

**Comment by genryxy** [comment]
While ITs fail because of unsuccessful start of container for all tests https://github.com/artipie/npm-adapter/pull/181/checks?check_run_id=1832154931#step:5:1730 It looks unrelated to changes that were made in this PR. It is possible to restart later will help

**Review by olenagerasimova — DISMISSED** [review]
@genryxy thanks, looks good to merge

**Comment by g4s8** [comment]
@genryxy please check: many tests are failing.

**Comment by genryxy** [comment]
@g4s8 I think there are some problems with github actions because this problem is similar to recent PRs with ITs failing in `artipie` and `docker-adapter`
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
...
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=testcontainersofficial/sshd:1.0.0, imagePullPolicy=DefaultPullPolicy())
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1279)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:613)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:320)
	... 105 more
Caused by: com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: testcontainersofficial/ryuk:0.3.0"}
...
```

**Comment by genryxy** [comment]
@olenagerasimova could you please take a look again
@g4s8 please check/merge

**Review by olenagerasimova — APPROVED** [review]
@genryxy thanks again

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#181` is not assigned, can't get performer

**Pull request merged**
