### PR TITLE
#36 - Extract Publish interface

### PR DESCRIPTION
**Pull request by genryxy**
Part of #36 
`Publish` interface was extracted. The main logic for `npm publish` was moved to `CliPublish` from `Npm`. 
Next I will implement `CurlPublish` and add it to `NpmSlice`.

### CODE REVIEW

**Comment by g4s8** [comment]
@olenagerasimova @genryxy I think we need to discuss it with our users first, maybe we'll have another solution

**Comment by olenagerasimova** [comment]
@g4s8 @genryxy hm, generally I like the course of these changes, but I'd suggested to extract class from `updateMetaFile()` method, which will simply update metadata file, we'll be able to test this class separately and make `CliPublish` implementation smaller.

**Comment by genryxy** [comment]
@olenagerasimova extracted logic of meta update to class `MetaUpdate.ByJson`, next it is possible to create `MetaUpdate.ByTgz`

**Comment by olenagerasimova** [comment]
@genryxy thanks, looks good to merge. Also, could you please try to make PRs smaller? About 150 changed lines is already enough for the PR.

**Review by olenagerasimova — APPROVED** [review]

**Comment by 0crat** [comment]
Job was finished in 25 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by genryxy** [comment]
@olenagerasimova yes, sorry for such large PR. I'll try to make them smaller.

**Pull request merged**
