### PR TITLE
#122 - Fixed & refactored NpmCommandsTest

### LINKED ISSUE #122: Fix and enable integration test NpmCommandsTest
`NpmCommandsTest` is currently disabled. It seems that the problem with the test is rather minor and caused by change of paths in the repository. The test should be fixed and enabled at least for Unix OS

### PR DESCRIPTION
**Pull request by olegmoz**
Closes #122
Fixed & refactored `NpmCommandsTest`

### CODE REVIEW

**Review by olenagerasimova — CHANGES_REQUESTED** [review]
@olegmoz this test executes some npm commands on the local machine - such approach does not seem good. Maybe we should at least add todo to migrate to docker container here?

**Comment by olegmoz** [comment]
@olenagerasimova thanks, I have added an issue about running NPM in Docker container: https://github.com/artipie/npm-adapter/issues/127

**Review by olenagerasimova — APPROVED** [review]
@olegmoz thanks

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#126` is not assigned, can't get performer

**Pull request merged**
