### PR TITLE
Feature/multi module project

### PR DESCRIPTION
**Pull request by brastak**
For https://github.com/artipie/npm-proxy-adapter/issues/32 - move project as sub-dir with history

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#82](https://github.com/artipie/npm-adapter/issues/82) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/a5ceaf92-094a-44f1-b7f6-52275ff16e25); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat assign @victornoel

**Comment by 0crat** [comment]
> @0crat assign @victornoel  ([here](https://github.com/artipie/npm-adapter/issues/82#issuecomment-641848844))

@g4s8 This pull request [#82](https://github.com/artipie/npm-adapter/issues/82) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/db2dea7f-23a1-41ed-8c9c-689ef674c07c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by victornoel** [comment]
@brastak so if I understand well you use the filter-branch feature of git to copy the history but in a subdirectory? Can you share the command you used maybe?

**Comment by victornoel** [comment]
@brastak another comment: I don't see any pom.xml that sets up this new project as a submodule of the current project, isn't that what should have been done? Or is there some next step such as moving everything into the npm-adapter project?

**Comment by brastak** [comment]
> @brastak so if I understand well you use the filter-branch feature of git to copy the history but in a subdirectory? Can you share the command you used maybe?

@victornoel I have used the following:
```
git subtree add --prefix npm-proxy-adapter git@github.com:artipie/npm-proxy-adapter.git master
```

**Comment by brastak** [comment]
> @brastak another comment: I don't see any pom.xml that sets up this new project as a submodule of the current project, isn't that what should have been done? Or is there some next step such as moving everything into the npm-adapter project?

@victornoel It's my bad - I have forgotten to push it. fixed now

**Comment by victornoel** [comment]
@brastak I'm not sure it is a good idea to start using git subtree here, this implies some git management stuffs that we don't want to have. But @g4s8 should decide that in the end. Can you give your opinion? IMHO either we just copy the source tree as it is, or we add the history with git filter-branch, but subtree seems to be unneeded because in the end we just want to have one repository without any special handling for the two modules in git.

**Comment by g4s8** [comment]
> @brastak I'm not sure it is a good idea to start using git subtree here, this implies some git management stuffs that we don't want to have. But @g4s8 should decide that in the end. Can you give your opinion? IMHO either we just copy the source tree as it is, or we add the history with git filter-branch, but subtree seems to be unneeded because in the end we just want to have one repository without any special handling for the two modules in git.

@victornoel we're going to remove npm-proxy repository and move all code to npm repo. So I think we need to keep the history of commits to analyze it later if needed.

**Comment by victornoel** [comment]
@g4s8 yes I don't see a problem with that, I see a problem with using subtree, which is meant to integrate two repositories together. But maybe I'm missing something and actually it's not using subtree in the resulting PR?

**Comment by victornoel** [comment]
@g4s8 @brastak I've checked the tree with git and it indeed does not seem to have anything subtree related (except some comment in one commit but it's not problematic), so it seems to be ok like this :)

**Comment by 0crat** [comment]
Job was finished in 27 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/artipie/npm-adapter/issues/82#issuecomment-642624092))

@victornoel This is what I know about this job in CT2E6TK9B, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#82](https://github.com/artipie/npm-adapter/issues/82) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CT2E6TK9B?q=%7Bjob%3A%27gh%3Aartipie%2Fnpm-adapter%2382%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@g4s8 0crat didn't pay me here either

**Comment by victornoel** [comment]
@g4s8 actually it paid me but didn't notify me

**Pull request merged**
