### PR TITLE
#119 - Add disabled test for time in meta.json

### PR DESCRIPTION
**Pull request by genryxy**
Part of #119 
Add disabled test for time in `meta.json` to check modified time and version time.

### CODE REVIEW

**Review by olegmoz — CHANGES_REQUESTED** [review]
@genryxy I do not see good reason to make it an integration test, maybe it will be more appropriate to create a unit test on level of `Npm` class or even lower?

**Comment by genryxy** [comment]
@olegmoz thanks, moved test to `MetaTest`

**Review by olegmoz — APPROVED** [review]
@genryxy thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#133` is not assigned, can't get performer

**Pull request merged**
