### PR TITLE
Use github actions instead of travis

### PR DESCRIPTION
**Pull request by Sammers21**

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#16](https://github.com/artipie/npm-adapter/issues/16) is assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/71cb3033-be8e-4d50-9187-cbeb96277f1f); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 13 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job audit: `ARC` didn't merge or close PR, performer @iakunin[/z](https://www.0crat.com/u/iakunin)[/z](https://www.0crat.com/u/iakunin) didn't make CR comments

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
Order was finished: +20 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-adapter/issues/16#issuecomment-584512537))

@g4s8 Job `gh:artipie/npm-adapter#16` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@Sammers21 2 puzzles [#85](https://github.com/artipie/npm-adapter/issues/85), [#86](https://github.com/artipie/npm-adapter/issues/86) are still not solved.

**Pull request merged**
