### PR TITLE
#36 - Add unit tests for meta update by tgz and curlPublish

### LINKED ISSUE #36: Npm.java:119-124: Implement metadata update by using tgz...
The puzzle `27-b5f30c4d` from #27 has to be resolved: 

https://github.com/artipie/npm-adapter/blob/7b306cec039e450c8f0e55a6f571c4362b1e7f90/src/main/java/com/artipie/npm/Npm.java#L119-L124

The puzzle was created by paulodamaso on 17-Mar-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by genryxy**
Closes #36
Added unit tests for meta update by tgz and `CurlPublish`. 
Marked `Npm` class as deprecated because it was replaced with `Publish` interface and `CurlPublish` and `CliPublish` implementations.

### CODE REVIEW

**Comment by genryxy** [comment]
@g4s8 please check/merge

**Review by olenagerasimova — APPROVED** [review]
@genryxy thanks, looks good to merge

**Review by g4s8 — CHANGES_REQUESTED** [review]
@genryxy I think we need to be sure that our clients don't use `Npm` class in code. If they use, we need to deprecate `Npm` calls to new classes instances

**Comment by genryxy** [comment]
@g4s8 thanks, marked `Npm` class as deprecated

**Review by g4s8 — APPROVED** [review]
@genryxy thanks

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#187` is not assigned, can't get performer

**Pull request merged**
