### PR TITLE
Generate random name for file. closes #78

### LINKED ISSUE #78: possible data corruption or http:500 in case of parallel npm package upload
If two differet user desides upload the same revision of npm package, UploadSlice.class  will generate 
the same name for temp file.
In that case we must return 409 or do something else. Possible solution: generate random name for temp file on the fly.

### PR DESCRIPTION
**Pull request by artemlazarev**
Generate random name for temp file. closes #78

### CODE REVIEW

**Comment by 0crat** [comment]
@artemlazarev[/z](https://www.0crat.com/u/artemlazarev) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by artemlazarev** [comment]
@g4s8 sad kitty wait the review

**Comment by g4s8** [comment]
@artemlazarev please ask @brastak to review your changes

**Comment by g4s8** [comment]
@artemlazarev please resolve merge conflicts

**Comment by artemlazarev** [comment]
@brastak i had fix merge conflicts. Please give approval again

**Comment by artemlazarev** [comment]
@g4s8 ready to merge

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#81` is not assigned, can't get performer

**Pull request merged**
