### PR TITLE
#155 - dist-tags ls fully implemented

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #155 
Fully implemented `dist-tags ls` command

### CODE REVIEW

**Review by genryxy — APPROVED** [review]
@olenagerasimova thanks, looks good to me

**Comment by olenagerasimova** [comment]
@olegmoz please, take a look/merge

**Review by olegmoz — APPROVED** [review]
@olenagerasimova thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#159` is not assigned, can't get performer

**Pull request merged**
