### PR TITLE
Aibolit style checker

### PR DESCRIPTION
**Pull request by acheshkov**
Aibolit style checker integrated to CI

### CODE REVIEW

**Comment by 0crat** [comment]
This pull request [#84](https://github.com/artipie/npm-adapter/issues/84) is assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ae6ddc26-7332-4b42-8a07-05645c96d878); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-adapter/issues/84#issuecomment-651123634))

@g4s8 The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#84](https://github.com/artipie/npm-adapter/issues/84), please stop working. Reason for job resignation: Order was cancelled

**Comment by g4s8** [comment]
@acheshkov this repository has two Maven modules: `npm-hosted-adapter ` and `npm-proxy-adapter`, can you please change `./src/main/java` to `npm-hosted-adapter/src/main/java` and `npm-proxy-adapter/src/main/java` ?

**Comment by acheshkov** [comment]
> npm-proxy-adapter/src/main/java

@g4s8 done

**Comment by 0crat** [comment]
This pull request [#84](https://github.com/artipie/npm-adapter/issues/84) is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/f5644856-03c7-4d83-b3ee-67f38a12b652); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Pull request [#84](https://github.com/artipie/npm-adapter/issues/84) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Pull request closed without merging**
