### PR TITLE
31 download

### PR DESCRIPTION
**Pull request by Guseyn**
Not for review til #33 is merged.

### CODE REVIEW

**Comment by paulodamaso** [comment]
@g4s8 I can reviewit once #33 is done

**Comment by 0crat** [comment]
This pull request [#34](https://github.com/artipie/npm-adapter/issues/34) is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/d26f9988-f459-4284-9485-f3f23a7e5713); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by fanifieiev** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse  ([here](https://github.com/artipie/npm-adapter/issues/34#issuecomment-599819375))

@fanifieiev The user @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) resigned from [#34](https://github.com/artipie/npm-adapter/issues/34), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse  ([here](https://github.com/artipie/npm-adapter/issues/34#issuecomment-599819375))

@fanifieiev Job refused in 7 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
This pull request [#34](https://github.com/artipie/npm-adapter/issues/34) is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/bec79b5f-7e06-4ebc-a208-6e51d6246fff); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

**Comment by g4s8** [comment]
@0crat assign @Vatavuk

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat assign @Vatavuk  ([here](https://github.com/artipie/npm-adapter/issues/34#issuecomment-601053036))

@g4s8 Job [#34](https://github.com/artipie/npm-adapter/issues/34) is closed, can't start order

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/npm-adapter/issues/34#issuecomment-601055978))

@g4s8 The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#34](https://github.com/artipie/npm-adapter/issues/34), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#34` is not assigned, can't get performer

**Pull request merged**
