### PR TITLE
#141 - Use TestResource in NpmIT

### PR DESCRIPTION
**Pull request by genryxy**
Part of #141 
Use `TestResource` in `NpmIT` in the same way as in Artipie. Disabled `npmInstall` test

### CODE REVIEW

**Comment by genryxy** [comment]
@olegmoz could you please check why `NpmProxyITCase` began to fail, I don't have any idea about this

**Comment by olegmoz** [comment]
@genryxy it seems that NPM client prints notice about new version of NPM client available, see:
```
Error:  com.artipie.npm.proxy.NpmProxyITCase.assetNotFound  Time elapsed: 9.436 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: a string containing "Not Found - GET http://host.testcontainers.internal:33515/npm-proxy/assetNotFound"
     but: was "npm
 
notice
 
npm
 
notice
 New patch version of npm available! 7.0.2 -> 7.0.3
npm
 notice
 Changelog: <https://github.com/npm/cli/releases/tag/v7.0.3>
npm 
notice
 Run `npm install -g npm@7.0.3` to update!

npm notice
 

npm ERR!
 could not detect node name from path or package


npm ERR! A complete log of this run can be found in:
npm 
ERR!     /root/.npm/_logs/2020-10-23T09_41_09_756Z-debug.log
```

Also log file `/root/.npm/_logs/2020-10-23T09_41_09_756Z-debug.log` is mentioned, maybe you can run locally and see what's is inside this file

**Comment by olegmoz** [comment]
@genryxy I have disabled proxy tests and created a puzzle for re-enabling them: https://github.com/artipie/npm-adapter/issues/144

**Comment by genryxy** [comment]
@olegmoz thanks, please take a look. I changed docker image in `NpmProxyITCase` from `node:latest` to `node:14-alpine` to fix build

**Comment by genryxy** [comment]
@olegmoz sorry, I just saw a new ticket about problem with `NpmProxyITCase`. I will change docker change in the created issue

**Comment by olegmoz** [comment]
@genryxy great job! Could you please update this PR to re-enable tests and solve https://github.com/artipie/npm-adapter/issues/144 ? Or create separate PR for this fix

**Comment by genryxy** [comment]
@olegmoz created separate PR for fix #146

**Review by olegmoz — APPROVED** [review]
@genryxy thanks, merging

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#142` is not assigned, can't get performer

**Pull request merged**
