### PR TITLE
#36 - Unit tests for meta update by json and cliPublish

### PR DESCRIPTION
**Pull request by genryxy**
Part of #36 
Added unit tests for meta update by json and `CliPublish`

### CODE REVIEW

**Review by olenagerasimova — APPROVED** [review]
@genryxy thanks, looks good to me

**Comment by genryxy** [comment]
@g4s8 please check/merge

**Comment by genryxy** [comment]
@g4s8 could you please merge

**Comment by 0crat** [comment]
Job `gh:artipie/npm-adapter#180` is not assigned, can't get performer

**Pull request merged**
